name: Build and Deploy to Azure Container Apps

on:
  push:
    branches:
      - master

env:
  REGISTRY: docker.io
  IMAGE_PRODUCT: ${{ secrets.DOCKER_USERNAME }}/product-service
  IMAGE_ORDER: ${{ secrets.DOCKER_USERNAME }}/order-service

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # ✅ Aquí agregas la validación de secretss
      - name: Validar secrets necesarios
        run: |
          if [ -z "${{ secrets.AZURE_RESOURCE_GROUP }}" ]; then
            echo "ERROR: AZURE_RESOURCE_GROUP no está configurado."
            exit 1
          fi
          if [ -z "${{ secrets.AZURE_CONTAINERAPP_PRODUCT }}" ]; then
            echo "ERROR: AZURE_CONTAINERAPP_PRODUCT no está configurado."
            exit 1
          fi
          if [ -z "${{ secrets.AZURE_CONTAINERAPP_ORDER }}" ]; then
            echo "ERROR: AZURE_CONTAINERAPP_ORDER no está configurado."
            exit 1
          fi
          echo "Todos los secrets requeridos están configurados correctamente."

      - name: Mostrar estructura de carpetas
        run: ls -R

      # ✅ Verificar existencia de Dockerfile product-service-
      - name: Verificar existencia de Dockerfile product-service
        run: |
          if [ ! -f ./product-service/Dockerfile ]; then
            echo "ERROR: Dockerfile not found in product-service"
            exit 1
          fi

      # ✅ Verificar existencia de Dockerfile order-service
      - name: Verificar existencia de Dockerfile order-service
        run: |
          if [ ! -f ./order-service/Dockerfile ]; then
            echo "ERROR: Dockerfile not found in order-service"
            exit 1
          fi
      # Checkout y configuración Docker, Java, etc.

      - name: Build product-service with Maven
        run: mvn -f ./product-service/pom.xml clean package -DskipTests
      - name: Build and push product-service image
        uses: docker/build-push-action@v4
        with:
          context: ./product-service
          push: true
          tags: ${{ env.IMAGE_PRODUCT }}:latest
      - name: Build order-service with Maven
        run: mvn -f ./order-service/pom.xml clean package -DskipTests
      - name: Build and push order-service image
        uses: docker/build-push-action@v4
        with:
          context: ./order-service
          push: true
          tags: ${{ env.IMAGE_ORDER }}:latest

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Container App - product-service
        run: |
          echo "az containerapp update --name product-service --resource-group shopping-cart --image robertillo545445/product-service:latest"
          az containerapp update \
          --name product-service \
          --resource-group shopping-cart \
          --image robertillo545445/product-service:latest

      - name: Deploy to Azure Container App - order-service
        run: |
          az containerapp update \
            --name order-srvice \
            --resource-group shopping-cart \
            --image robertillo545445/order-service:latest